baseURL = "http://example.org/"
title = "Sabine (Bertram) Schaller"
theme = ["hugo-coder", "webmonetization"]
languageCode = "en-us"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[markup]
  defaultMarkdownHandler = "blackfriday"

[params]
  author = "Sabine (Bertram) Schaller"
  info = "Backend Engineer, Consultant, Founder"
  description = "Sabine Schaller's personal website"
  keywords = "developer,personal"
  avatarurl = "img/sabines-r&d.JPG"
  #gravatar = "john.doe@example.com"
  monetization = "$ilp.uphold.com/wx88AUrqG2aY"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

#   footercontent = "Enter a text here."
  hideFooter = false
  hideCredits = true
  hideCopyright = false
  since = 2021

  enableTwemoji = false

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = ["css/custom.css"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/sabinebertram/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://linkedin.com/in/sabinebertram/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Contact"
  weight = 2
  url = "contact/"